language: node_js
node_js:
- '0.10'
before_script:
- npm install grunt-cli -g
deploy:
  provider: npm
  email: dmitry@itis.cs.msu.ru
  skip_cleanup: true
  api_key:
    secure: AFM9Uqbv00h5q6uyUoh8FoOfE+68n9XTnTYKYDsE6H8xvl5tncVFZHlgnHqxsHHxUnb54tOI9vPzLIaxKz+E5TFd9aeGTCHh5AGGzcPdtnTMUbekXeqMiyVilKnycDaLtaUreA0NQUMnbLA5d1piTDkmdrYlsBIZ8zAuGLS6GeMrLyGFCYeZua94xcLsZzlNDLgdBUMUSiMYin+Ey+IfZWmyQFNX7gxx3X40wjY6tpfwcnLfwtxAwOhcRAJYH5XwUyX5+3CXCJrHR0uzcSbltLOZEafTdOnsUQrq5Ad+cRix9wh6oGdCeTbHOX7JSPJiw4OrXixTIS8mRxmXKoi7KM7DR+il54udRnPPonwP+7MkKeBaeuG9mEm634P0dy5T98PdQbfmiXT2VsPLs/PpuMZyogEYaySYbp/W74PVxBjvL1WuiPrDeWw9RG6aWc6tKsfr7/CnEeM7mTxzATw02Hxc+zF93TJUAo/pchS9nKRzkpeIQMKNpGX6XsNLgS+jC6IGAonS+/+kFhNqR8A6Fi4FGCmeXkSaLHuPN/L1+sDAl/XU0+qRKu93O1zcJsP4Tqjj7K6gGytrphktb3KjUCaksOG1RR3C8lSLt1Fi1C//A1udjrtvH9Bv25YnmDCqXf7vKuRtX4AkKSfkqLHdlw5uuyc5jkqpPpq2xOgJv/c=
  on:
    tags: true
